---
filters: {}
rules:
  preset-ja-technical-writing:
    "sentence-length": false
    "no-exclamation-question-mark": false
  "@textlint-ja/no-synonyms": true
  "preset-ja-spacing":
    "ja-space-between-half-and-full-width":
      "space": "always"
    "ja-space-around-code":
      "before": true
      "after": true
    "ja-no-space-around-parentheses": false
    "ja-nakaguro-or-halfwidth-space-between-katakana": false
    "ja-space-after-exclamation": false
    "ja-space-after-question": false
  "@proofdict/proofdict":
    dictURL: https://react-native-jp.github.io/proof-dictionary/
